"""add geocoding fields to address

Revision ID: 87895dff04bd
Revises: e3289cffba19
Create Date: 2026-09-14 15:39:10.895228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87895dff04bd'
down_revision: Union[str, Sequence[str], None] = 'e3289cffba19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('formatted_address', sa.String(), nullable=True))
    op.add_column('addresses', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('addresses', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'longitude')
    op.drop_column('addresses', 'latitude')
    op.drop_column('addresses', 'formatted_address')
    # ### end Alembic commands ###
