"""add geocoding fields to restaurant

Revision ID: e13ec11696de
Revises: bef5a138d11c
Create Date: 2026-09-15 11:49:32.086277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e13ec11696de'
down_revision: Union[str, Sequence[str], None] = 'bef5a138d11c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('address_line', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('formatted_address', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('restaurants', sa.Column('longitude', sa.Float(), nullable=True))
    op.drop_column('restaurants', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('restaurants', 'longitude')
    op.drop_column('restaurants', 'latitude')
    op.drop_column('restaurants', 'formatted_address')
    op.drop_column('restaurants', 'address_line')
    # ### end Alembic commands ###
